# Generated by Django 4.2.6 on 2023-10-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the problem', max_length=100)),
                ('description', models.TextField(help_text='Description of the problem', max_length=1000)),
                ('category', models.ForeignKey(help_text='Category of the problem', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructions.category')),
            ],
        ),
    ]
